#!/usr/bin/env bash
# scripts/e2e/negative/assert-default-deny.sh
#
# NEGATIVE assertion for the ADR-07 four-pack #4 default-deny NetworkPolicy
# baseline (issue #170). Two layers:
#
#   (a) STRUCTURAL — the `aegis-default-deny` NetworkPolicy was GENERATED by
#       Kyverno into the workload namespace, with an empty podSelector (all pods)
#       and both Ingress + Egress policy types.
#   (b) BEHAVIOURAL — it ACTUALLY BLOCKS cross-namespace traffic. A client in a
#       non-workload namespace can reach an OPEN server (positive control) but
#       CANNOT reach a server inside the default-denied workload namespace.
#
# Layer (b) needs a NetworkPolicy-ENFORCING CNI. kind's default kindnet does NOT
# enforce NetworkPolicy — the kind workflow installs Calico first; k3s ships an
# enforcing controller by default. This script assumes that is already in place
# (substrate-agnostic: cluster + CNI are the caller's job).
#
# Usage: KUBECONFIG=... ./scripts/e2e/negative/assert-default-deny.sh
set -euo pipefail

E2E_NS="${E2E_NS:-aegis-e2e}"     # default-denied workload namespace (golden-path)
PROBE_NS="${PROBE_NS:-e2e-probe}" # NON-aegis-* client namespace (no policies apply)

# Server image, digest-pinned: the server runs in $E2E_NS, which require-digest
# Enforce gates — so it MUST carry a digest. nginx-unprivileged serves on :8080.
SERVER_IMAGE="nginxinc/nginx-unprivileged:1.27-alpine@sha256:65e3e85dbaed8ba248841d9d58a899b6197106c23cb0ff1a132b7bfe0547e4c0"
# Client image, digest-pinned busybox (wget). Runs in $PROBE_NS (unconstrained).
CLIENT_IMAGE="busybox:1.37@sha256:9532d8c39891ca2ecde4d30d7710e01fb739c87a8b9299685c63704296b16028"

cleanup() {
  kubectl delete namespace "$PROBE_NS" --ignore-not-found --wait=false >/dev/null 2>&1 || true
  kubectl delete pod deny-server open-client deny-client -n "$E2E_NS" --ignore-not-found >/dev/null 2>&1 || true
  kubectl delete svc deny-svc -n "$E2E_NS" --ignore-not-found >/dev/null 2>&1 || true
}
trap cleanup EXIT

# ── (a) STRUCTURAL: the generated NetworkPolicy is a real default-deny ────────
echo "==> [default-deny] (a) STRUCTURAL: aegis-default-deny present + deny-all shape"
kubectl get networkpolicy aegis-default-deny -n "$E2E_NS" >/dev/null
SELECTOR="$(kubectl get networkpolicy aegis-default-deny -n "$E2E_NS" -o jsonpath='{.spec.podSelector}')"
PTYPES="$(kubectl get networkpolicy aegis-default-deny -n "$E2E_NS" -o jsonpath='{.spec.policyTypes}')"
# Empty podSelector ({}) == selects EVERY pod in the namespace. With Ingress +
# Egress listed and NO ingress/egress rules, this is a total deny-all.
if [ "$SELECTOR" != "{}" ]; then
  echo "    FAIL: podSelector is '$SELECTOR', expected '{}' (all pods)."; exit 1
fi
case "$PTYPES" in
  *Ingress*) : ;; *) echo "    FAIL: policyTypes '$PTYPES' missing Ingress."; exit 1 ;;
esac
case "$PTYPES" in
  *Egress*) : ;; *) echo "    FAIL: policyTypes '$PTYPES' missing Egress."; exit 1 ;;
esac
echo "    OK: podSelector={} (all pods), policyTypes=$PTYPES, no allow rules — deny-all."

# ── set up server (in denied ns) + open server (in probe ns) ─────────────────
echo "==> [default-deny] Bringing up server in $E2E_NS and client namespace $PROBE_NS"
kubectl create namespace "$PROBE_NS" --dry-run=client -o yaml | kubectl apply -f -

# Server inside the DEFAULT-DENIED namespace. No readiness probe on purpose:
# under default-deny, kubelet HTTP probes can be dropped by the CNI, which would
# stall Ready forever; with no probe the container is Ready once Running.
kubectl run deny-server -n "$E2E_NS" --image="$SERVER_IMAGE" --port=8080 \
  --labels="app=deny-server" --restart=Never >/dev/null
kubectl expose pod deny-server -n "$E2E_NS" --name=deny-svc --port=8080 --target-port=8080 >/dev/null

echo "==> [default-deny] Waiting for server pod Ready"
kubectl wait --for=condition=Ready pod/deny-server -n "$E2E_NS" --timeout=120s
DENY_SVC_IP="$(kubectl get svc deny-svc -n "$E2E_NS" -o jsonpath='{.spec.clusterIP}')"
echo "    deny-svc ClusterIP: $DENY_SVC_IP"

# ── (b1) POSITIVE CONTROL: client -> OPEN server (same probe ns) succeeds ─────
# Proves the client/wget mechanics + CNI datapath work, so a failure in (b2) is
# attributable to the default-deny policy, not to a broken test.
echo "==> [default-deny] (b1) POSITIVE control: client reaches an OPEN server"
# Same nginx image as the denied server (serves index.html at / with a 200), so
# positive and negative differ ONLY in which namespace the server sits in.
kubectl run open-server -n "$PROBE_NS" --image="$SERVER_IMAGE" --port=8080 \
  --labels="app=open-server" --restart=Never >/dev/null
kubectl expose pod open-server -n "$PROBE_NS" --name=open-svc --port=8080 --target-port=8080 >/dev/null
kubectl wait --for=condition=Ready pod/open-server -n "$PROBE_NS" --timeout=120s
OPEN_SVC_IP="$(kubectl get svc open-svc -n "$PROBE_NS" -o jsonpath='{.spec.clusterIP}')"

kubectl run open-client -n "$PROBE_NS" --image="$CLIENT_IMAGE" --restart=Never \
  --command -- wget -T 8 -q -O- "http://$OPEN_SVC_IP:8080/" >/dev/null
kubectl wait --for=jsonpath='{.status.phase}'=Succeeded pod/open-client -n "$PROBE_NS" --timeout=60s 2>/dev/null || true
OPEN_PHASE="$(kubectl get pod open-client -n "$PROBE_NS" -o jsonpath='{.status.phase}')"
if [ "$OPEN_PHASE" != "Succeeded" ]; then
  echo "    FAIL: positive control could not reach the OPEN server (phase=$OPEN_PHASE)."
  echo "          The test harness/datapath is broken — cannot trust the deny result."
  kubectl logs open-client -n "$PROBE_NS" 2>/dev/null | tail -5 | sed 's/^/      /' || true
  exit 1
fi
echo "    OK: client reached the OPEN server (positive control passes)."

# ── (b2) NEGATIVE: client -> server in the DEFAULT-DENIED namespace is BLOCKED ─
echo "==> [default-deny] (b2) NEGATIVE: client to $E2E_NS server must be BLOCKED"
kubectl run deny-client -n "$PROBE_NS" --image="$CLIENT_IMAGE" --restart=Never \
  --command -- wget -T 8 -q -O- "http://$DENY_SVC_IP:8080/" >/dev/null
# default-deny DROPS (not rejects) → wget hangs until -T timeout → exit != 0 →
# pod phase Failed. Admitted traffic would give phase Succeeded.
kubectl wait --for=jsonpath='{.status.phase}'=Failed pod/deny-client -n "$PROBE_NS" --timeout=60s 2>/dev/null || true
DENY_PHASE="$(kubectl get pod deny-client -n "$PROBE_NS" -o jsonpath='{.status.phase}')"
if [ "$DENY_PHASE" = "Succeeded" ]; then
  echo "    FAIL: client REACHED the default-denied server — NetworkPolicy not enforcing."
  echo "          (Is a NetworkPolicy-enforcing CNI installed? kindnet does NOT enforce.)"
  exit 1
fi
if [ "$DENY_PHASE" != "Failed" ]; then
  echo "    FAIL: deny-client ended in unexpected phase '$DENY_PHASE' (expected Failed/blocked)."
  kubectl describe pod deny-client -n "$PROBE_NS" 2>/dev/null | tail -20 | sed 's/^/      /' || true
  exit 1
fi
echo "    OK: client BLOCKED from the default-denied server (phase=Failed/timeout)."

echo "==> default-deny negative assertion PASSED (present + deny-all + actually blocks)."
